import { MONEYGRAPHY, NOTOSANS, SUIT } from "@/styles/fonts/fonts";
import "@/app/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        className={`${MONEYGRAPHY.variable} ${MONEYGRAPHY.className} antialiased bg-shadow-800 w-screen  `}
        // className={`${MONEYGRAPHY.variable} ${MONEYGRAPHY.className} antialiased bg-accent-purple w-screen`}
        // className={`${NOTOSANS.className} antialiased bg-accent-purple w-screen`}
      >
        {/* <div className="flex flex-row justify-center gap-[5%] h-full w-full "> */}
        <div className="flex justify-center h-full w-full ">
          {/* <AdBanner /> */}
          <div className="w-[500px] max-w-[500px] min-w-0 bg-darkBg text-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
